### PR TITLE
fix: the default schedule to only run every 4th hour

### PR DESCRIPTION
**Pull request by benjyiw**
previously it was running "At every minute past every 4th hour"

### CODE REVIEW

**Comment by benjyiw** [comment]
validation failed because this is to the main branch and it only allows the alpha branch, but there is no alpha branch?

**Comment by benjyiw** [comment]
but we have that disabled? https://github.com/catalystsquad/chart-aws-ecr-creds/blob/main/.github/workflows/pull_request.yaml#L24

**Review by todpunk — APPROVED** [review]

**Comment by todpunk** [comment]
We can fix that when the other things are fixed.

**Pull request merged**
